---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Schedule - Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry-Run
        default: "null"
        required: false
      logLevel:
        description: Log-Level
        default: info
        required: false
      autodiscoverFilter:
        description: Autodiscover Filter
        default: "*"
        required: false
  schedule:
    #- cron: "0 * * * *" # Run every hour
    - cron: "0 */6 * * *" # Run every 6 hours
  push:
    branches:
      - main
    paths:
      - .renovaterc.json5
      - .github/workflows/schedule-renovate.yaml

env:
  LOG_LEVEL: info
  RENOVATE_DRY_RUN: false
  RENOVATE_CONFIG_FILE: .renovaterc.json5
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  RENOVATE_AUTODISCOVER: true
  RENOVATE_INTERNAL_CHECKS_FILTER: strict
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    #runs-on: arc-runner-set-faiph-dev
    steps:
      # # https://github.com/marketplace/actions/github-app-token
      # - name: Harden Runner
      #   uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      #   with:
      #     egress-policy: audit

      - name: Early exit if not gznzeus on issues or pull_request
        if: ${{ (github.event_name == 'issues' || github.event_name == 'pull_request') && github.event.sender.login != 'gznzeus' }}
        run: |
          echo "Not gznzeus, exiting early."
          exit 0

      # https://github.com/marketplace/actions/create-github-app-token
      - name: Generate Token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      # https://github.com/marketplace/actions/checkout
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Override default config from dispatch variables
        run: |
          echo "RENOVATE_DRY_RUN=${{ github.event.inputs.dryRun || env.RENOVATE_DRY_RUN }}" >> "${GITHUB_ENV}"
          echo "LOG_LEVEL=${{ github.event.inputs.logLevel || env.LOG_LEVEL }}" >> "${GITHUB_ENV}"
          echo "RENOVATE_AUTODISCOVER_FILTER=${{ github.repository_owner }}/${{ github.event.inputs.autodiscoverFilter || '*' }}" >> "${GITHUB_ENV}"

      # https://github.com/marketplace/actions/renovate-bot-github-action
      - name: Renovate
        uses: renovatebot/github-action@f8af9272cd94a4637c29f60dea8731afd3134473 # v43.0.12
        with:
          configurationFile: "${{ env.RENOVATE_CONFIG_FILE }}"
          token: "${{ steps.app-token.outputs.token }}"
        #env:
        #  RENOVATE_PRINT_CONFIG: "true"
        #  RENOVATE_HOST_RULES: |
        #    [
        #      {
        #        matchHost: "docker.io",
        #        hostType: "docker",
        #        username: "${{ secrets.DOCKER_IO_USER }}",
        #        password: "${{ secrets.DOCKER_IO_TOKEN }}",
        #      },
        #    ]
